# Temporal Expression Extraction Using LSTM RNN 

Data Preprocessing

In [1]:
import csv 
import collections
import math 
import random
import numpy as np 
import tensorflow as tf 


# preparing trainind Data
count_line = 0
training_list = []
label_value=""

def search(x,y,z,lst,idx):         # x -> paragraph_id  ; y-> line_no ; z-> token_no
    #print("index : ",idx)
    for i in range(idx,len(lst)):
        check_list = lst[i]
        #print(check_list)
        #newl = check_list
        para_id = check_list[0]
        line_no = check_list[1]
        token_no = check_list[2]
        
        nn = []
        #print(x,'=',para_id,y,line_no,z,'=',token_no)
        if para_id==x and line_no==y and token_no==z:
            #newl.append("timex3")
            label_value = 1
            #prin(check_list)
            idx = i + 1
            #print(check_list,label_value)
            string = ""
            for j in range(len(check_list)):
                single_val = check_list[j]
                single_val = single_val.rstrip("\n")
                nn.append(single_val)
                #string += single_val + "\t"
            #print(string,"\t",label_value) #
            nn.append(label_value)
            training_list.append(nn)
            return idx
        else:
            label_value = 0
            #prin(check_list)
            #newl.append("O")
            string = ""
            for j in range(len(check_list)):
                single_val = check_list[j]
                single_val = single_val.rstrip("\n")
                nn.append(single_val)
                #string += single_val + "\t"
            #print(string,"\t",nvalue) #
            nn.append(label_value)
            training_list.append(nn)
            #training_list.append(newl)

            
            
def make_word_List():
    words = []
    
    for i in range(len(training_list)):
        #print(training_list[i])
        ks = training_list[i]
        string = ks[3]
        isYes = False
        for j in range(len(string)):
            ch = string[j]
            if ch >='a' and ch <='z':
                isYes = True
                break
            elif ch >='A' and ch <='Z':
                isYes = True
                break
            elif ch >='0' and ch <='9':
                isYes = True
                break
        if isYes == True:
            words.append(string)
        else:
            words.append("UNK")
                     
    return words

def main():
    motherlist = []
    #clone = [] 
    extent_list = []
    idx=0
    #  time_extent.tab = extent_list
    with open("Dataset\\tempeval-training-2\\english\\data\\timex-extents.tab","r") as timex:
        for line in timex:
            lst = line.split("\t")
            extent_list.append(lst)
            #print(lst)
    #try1 = basSegmentation.tab = motherlist
    with open("Dataset\\tempeval-training-2\\english\\data\\base-segmentation.tab","r") as opn:
        for line in opn:
            lst = line.split("\t")
            motherlist.append(lst)
            #clone.append(lst)
            #print(lst)
    for i in range(len(extent_list)):
        nlst = extent_list[i]
        #print(nlst)
        x = nlst[0]
        y = nlst[1]
        z = nlst[2]
        #nlst[3] = nlst[3].rstrip("\n")
        idx = search(x,y,z,motherlist,idx)
        #print(i)
        #print(x,y,z)
    checked_line_number = len(motherlist)
    #print(idx,checked_line_number)
    if idx < checked_line_number :
        for i in range(idx,checked_line_number):
            remain_list = motherlist[i]
            out = ""
            nn=[]
            label_value = 0
            for j in range(len(remain_list)):
                single_val = remain_list[j]
                single_val = single_val.rstrip("\n")
                nn.append(single_val)
                #out += xxt + "\t"
            nn.append(label_value)
            #print(nn)
            training_list.append(nn)
            #print(out,"\t","O") #
    print("DONE!!!")
    global words 
    words = make_word_List()
    print(len(words))

if __name__== '__main__':
    main()

sep = "===================="    
print(sep)

print(words[:15])

for i in range(len(training_list)):
    if(training_list[i][2] == "0" ):
        count_line = count_line + 1 
        
#Line Information 
print(sep)
print(count_line)
print(sep)
word_per_line = len(words)/count_line
print(sep)
print(word_per_line)


paragraph_list = []
for k in range(len(training_list)):
    paragraph_list.append(training_list[k][0])
    


print(sep)
for k in range(100):
    print(training_list[k]) 
print(sep)

DONE!!!
53450
['On', 'the', 'other', 'hand', 'UNK', 'it', "'s", 'turning', 'out', 'to', 'be', 'another', 'very', 'bad', 'financial']
2176
24.563419117647058
['ABC19980108.1830.0711', '0', '0', 'On', 0]
['ABC19980108.1830.0711', '0', '1', 'the', 0]
['ABC19980108.1830.0711', '0', '2', 'other', 0]
['ABC19980108.1830.0711', '0', '3', 'hand', 0]
['ABC19980108.1830.0711', '0', '4', ',', 0]
['ABC19980108.1830.0711', '0', '5', 'it', 0]
['ABC19980108.1830.0711', '0', '6', "'s", 0]
['ABC19980108.1830.0711', '0', '7', 'turning', 0]
['ABC19980108.1830.0711', '0', '8', 'out', 0]
['ABC19980108.1830.0711', '0', '9', 'to', 0]
['ABC19980108.1830.0711', '0', '10', 'be', 0]
['ABC19980108.1830.0711', '0', '11', 'another', 0]
['ABC19980108.1830.0711', '0', '12', 'very', 0]
['ABC19980108.1830.0711', '0', '13', 'bad', 0]
['ABC19980108.1830.0711', '0', '14', 'financial', 0]
['ABC19980108.1830.0711', '0', '15', 'week', 1]
['ABC19980108.1830.0711', '0', '16', 'for', 0]
['ABC19980108.1830.0711', '0', '17', 'Asia

Give Integer Id to tokens and paragraph

In [2]:
################### No Need Under this ###########################################
vocbulary_size = 53450
print(len(words))
    
print("--------------------------------------------------------------")
print("--------------------------------------------------------------")


def process_dataset(words):
    
    #count = [['UNK' , -1]] 
    count =[]
    count.extend(collections.Counter(words).most_common (vocbulary_size-1))
    dictionary = dict() 
    
    for word, _ in count:
        dictionary[word] = len(dictionary)
        
      
    data = []
#     unk_count = 0
    
    for word in words:
        if word in dictionary:
            index = dictionary[word]     
#         else:
#             index = 0
#             unk_count = unk_count + 1
        data.append(index)
    #print(unk_count)
#    count[0][1] = unk_count
    reverse_dictionary = dict(zip(dictionary.values(), dictionary.keys()))
    return data, count, dictionary, reverse_dictionary

data, count, dictionary, reverse_dictionary = process_dataset(words)

para_num , total_para , para_dictionary , para_reverse_dictionary = process_dataset(paragraph_list)
# data_test , count_test , dictionary_test , reverse_dictionary_test = process_dataset(test_words)

        

print(sep)
print(len(count))
print(sep)

print('Most common words :', count[:200],'len :', len(count))
print(sep)
print('Sample data',data[:30] ,'----------' , len(data) )

print(sep)
print(len(total_para))
print(sep)

print('sample_paragraph' , para_num[:6] ,'-------' , len(para_num))
print(sep)

print(training_list[:20])

### FINAL DATA LABELING
# Replacing words with integer id and replacing paragraph with integer id 
print(sep)
for cnt in range(len(training_list)):
    token = training_list[cnt][3] 
    training_list[cnt].append(token)
    training_list[cnt][0] = para_num[cnt]
    training_list[cnt][3] = data[cnt]

print(training_list[:20])

    
# #######################################################
# # Separate every Sentence



# para_line_list = []
# line_line_list = []
# line_token_list = []
# line_list = []
# label_line_list = []


# single_para_line = []
# single_line_line = []
# single_token_line = [] 
# single_line = [] 
# single_label_line =[]

# for indx in range(len(training_list)):
    
#     if( training_list[indx][2] == "0"):
        
#         para_line_list.append(single_para_line)
#         line_line_list.append(single_line_line)
#         line_token_list.append(single_token_line)
#         line_list.append(single_line)
#         label_line_list.append(single_label_line)
         
#         single_para_line = []
#         single_line_line = []
#         single_token_line = []
#         single_line = []
#         single_label_line = []
        
#         single_para_line.append(training_list[indx][0])
#         single_line_line.append(training_list[indx][1])
#         single_token_line.append(training_list[indx][2])
#         single_line.append(training_list[indx][3])
#         single_label_line.append(training_list[indx][4])
        
#     else:
           
#         single_para_line.append(training_list[indx][0])
#         single_line_line.append(training_list[indx][1])
#         single_token_line.append(training_list[indx][2])
#         single_line.append(training_list[indx][3])
#         single_label_line.append(training_list[indx][4])
        

# para_line_list.append(single_para_line)
# line_line_list.append(single_line_line)
# line_token_list.append(single_token_line)
# line_list.append(single_line)
# label_line_list.append(single_label_line)


# para_line_list.remove(para_line_list[0])
# line_line_list.remove(line_line_list[0])
# line_token_list.remove(line_token_list[0])
# line_list.remove(line_list[0])
# label_line_list.remove(label_line_list[0])

# ######################################################
# # Remove NonTemporal Sentence 
# print(sep)
# print(sep)
# count_timex_line = 0 

# for ln in range(len(line_list)):
#     if 'timex3' not in label_line_list[ln]:
#         continue
#     count_timex_line = count_timex_line + 1
#     print(sep)
#     print(para_line_list[ln])
#     print(line_line_list[ln])
#     print(line_token_list[ln])
#     print(line_list[ln])
#     print(label_line_list[ln])

# print(sep)
# print(sep)
# print(count_timex_line)
# print(sep)
# ######################################################


# for pk in range(10):
#     print(training_list[pk])

53450
--------------------------------------------------------------
--------------------------------------------------------------
7948
Most common words : [('UNK', 6035), ('the', 2283), ('of', 1370), ('to', 1287), ('a', 1175), ('in', 860), ('and', 850), ("'s", 589), ('million', 528), ('said', 527), ('for', 489), ('The', 441), ('that', 384), ('is', 353), ('from', 325), ('company', 302), ('it', 298), ('share', 268), ('its', 265), ('on', 255), ('or', 243), ('by', 243), ('with', 234), ('will', 231), ('at', 225), ('has', 224), ('as', 210), ('be', 208), ('was', 208), ('an', 183), ('are', 176), ('year', 173), ('have', 170), ('shares', 168), ('which', 165), ('about', 157), ('Mr.', 145), ('In', 141), ("'t", 133), ('cents', 127), ('would', 119), ('billion', 116), ('been', 115), ('n', 111), ('also', 110), ('he', 109), ('had', 107), ('more', 105), ('stock', 102), ('they', 100), ('this', 99), ('U.S.', 99), ('market', 95), ('quarter', 93), ('Inc.', 91), ('up', 91), ('but', 89), ('Corp.', 86), ('we

In [3]:
with open('name.tab', 'w') as csvfile:    
    writer = csv.writer(csvfile, delimiter='\t')
    for i in range(len(training_list)):
        writer.writerow(training_list[i])

In [4]:
from __future__ import print_function
import numpy as np
import pandas
np.random.seed(1337)  # for reproducibility

from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, TimeDistributedDense, Activation, Embedding
from keras.layers import LSTM
import codecs

Using TensorFlow backend.


In [5]:
# names = ['parano','senno','windx','wvalue','label','word']
data = pandas.read_csv("name.tab", sep='\t',header = None )
array = data.values

X = array[:,3:4]
Y = array[:,4:5]
Z = array[:,5]
print(data)

         0  1   2     3  4              5
0       33  0   0   743  0             On
1       33  0   1     1  0            the
2       33  0   2    74  0          other
3       33  0   3  1524  0           hand
4       33  0   4     0  0              ,
5       33  0   5    16  0             it
6       33  0   6     7  0             's
7       33  0   7  2285  0        turning
8       33  0   8   112  0            out
9       33  0   9     3  0             to
10      33  0  10    27  0             be
11      33  0  11   579  0        another
12      33  0  12   416  0           very
13      33  0  13  2161  0            bad
14      33  0  14   242  0      financial
15      33  0  15   188  1           week
16      33  0  16    10  0            for
17      33  0  17   520  0           Asia
18      33  0  18     0  0              .
19      33  1   0    11  0            The
20      33  1   1   242  0      financial
21      33  1   2  5849  0     assistance
22      33  1   3    14  0        

In [6]:
print(X)

[[743]
 [1]
 [74]
 ..., 
 [2227]
 [704]
 [0]]


In [7]:
print(Y)

[[0]
 [0]
 [0]
 ..., 
 [0]
 [0]
 [0]]


In [8]:
print(Z)

['On' 'the' 'other' ..., 'Advanced' 'Medical' '.']


In [9]:
dataframe = pandas.read_csv('name.tab', sep='\t', usecols=[4])
dataset = dataframe.values
dataset = dataset.astype('float32')

In [10]:
# split into train and test sets
train_size = int(len(dataset) * 0.70)
test_size = len(dataset) - train_size   
train, test = dataset[0:train_size,:], dataset[train_size:len(dataset),:]
print(len(train), len(test))

37414 16035


In [13]:
with open('train.tab', 'w') as csvfile_train:    
    writer = csv.writer(csvfile_train, delimiter='\t')
    for r in range(len(train)):
        writer.writerow(training_list[r])

dataframe_train = pandas.read_csv('train.tab', sep='\t', usecols=[4])
dataset_train = dataframe_train.values
dataset_train = dataset_train.astype('float32')

In [14]:
Z_test = []
with open('test.tab', 'w') as csvfile_test:    
    writer = csv.writer(csvfile_test, delimiter='\t')
    for p in range( len(train) , len(train)+len(test)):
        Z_test.append(training_list[p][5])
        writer.writerow(training_list[p])
        

dataframe_test = pandas.read_csv('test.tab', sep='\t', usecols=[4])
dataset_test = dataframe_test.values
dataset_test = dataset_test.astype('float32')

In [15]:
dataset_train = np.genfromtxt("train.tab", delimiter="\t")
dataset_test = np.genfromtxt("test.tab" , delimiter="\t")

maxlen= 1
embedding_dim = 64
batch_size = 32
epochs = 10
nb_word = 50000
# nb_tag = 2


x_train = dataset_train[:,3:4]
y_train= dataset_train[:,4]
x_test = dataset_test[:,3:4]
y_test = dataset_test[:,4]

X_train = sequence.pad_sequences(x_train, maxlen=maxlen)
X_test = sequence.pad_sequences(x_test, maxlen=maxlen)
Y_train = np.asarray(y_train, dtype='int32')
Y_test = np.asarray(y_test, dtype='int32')

In [16]:
# setmaxlen= 1,2,.... for higher dimensional data
print(X_train)

[[ 743]
 [   1]
 [  74]
 ..., 
 [7089]
 [   0]
 [  55]]


In [17]:
print(Y_train)
print(Y_test)
print(len(Y_test))

[0 0 0 ..., 0 0 0]
[0 0 0 ..., 0 0 0]
16035


In [18]:
len(Z_test)

16035

In [19]:
model = Sequential()
model.add(Embedding(nb_word, embedding_dim))
model.add(LSTM(16,activation='sigmoid', inner_activation='hard_sigmoid', dropout_W=0.1, dropout_U=0.01))


model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])


model.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
embedding_1 (Embedding)          (None, None, 64)      3200000     embedding_input_1[0][0]          
____________________________________________________________________________________________________
lstm_1 (LSTM)                    (None, 16)            5184        embedding_1[0][0]                
____________________________________________________________________________________________________
dense_1 (Dense)                  (None, 1)             17          lstm_1[0][0]                     
Total params: 3,205,201
Trainable params: 3,205,201
Non-trainable params: 0
____________________________________________________________________________________________________


In [20]:
model.fit(X_train, Y_train,
                batch_size=batch_size,
                nb_epoch=epochs)

Epoch 1/10
37414/37414 [==============================] - 163s - loss: 0.1393 - acc: 0.9703   
Epoch 2/10
37414/37414 [==============================] - 156s - loss: 0.0591 - acc: 0.9827   
Epoch 3/10
37414/37414 [==============================] - 156s - loss: 0.0504 - acc: 0.9844   
Epoch 4/10
37414/37414 [==============================] - 156s - loss: 0.0480 - acc: 0.9851   
Epoch 5/10
37414/37414 [==============================] - 157s - loss: 0.0474 - acc: 0.9850   
Epoch 6/10
37414/37414 [==============================] - 156s - loss: 0.0466 - acc: 0.9851   
Epoch 7/10
37414/37414 [==============================] - 156s - loss: 0.0461 - acc: 0.9851   
Epoch 8/10
37414/37414 [==============================] - 156s - loss: 0.0455 - acc: 0.9849   
Epoch 9/10
37414/37414 [==============================] - 158s - loss: 0.0451 - acc: 0.9849   
Epoch 10/10
37414/37414 [==============================] - 157s - loss: 0.0449 - acc: 0.9851   


In [21]:
predict = []
res = model.predict(X_test)
for i in res:
    predict.append(i)
    
    #if(res[i] == 1):
        #print(Z[i])

In [22]:
predict

[array([ 0.11464844], dtype=float32),
 array([ 0.0008852], dtype=float32),
 array([ 0.12474378], dtype=float32),
 array([ 0.00088713], dtype=float32),
 array([ 0.10934579], dtype=float32),
 array([ 0.0008852], dtype=float32),
 array([ 0.00088389], dtype=float32),
 array([ 0.12223373], dtype=float32),
 array([ 0.0008852], dtype=float32),
 array([ 0.11672376], dtype=float32),
 array([ 0.0008852], dtype=float32),
 array([ 0.11420792], dtype=float32),
 array([ 0.00088744], dtype=float32),
 array([ 0.0008852], dtype=float32),
 array([ 0.00088389], dtype=float32),
 array([ 0.08856998], dtype=float32),
 array([ 0.0008852], dtype=float32),
 array([ 0.09095952], dtype=float32),
 array([ 0.00089161], dtype=float32),
 array([ 0.0008852], dtype=float32),
 array([ 0.00088389], dtype=float32),
 array([ 0.10054669], dtype=float32),
 array([ 0.0008852], dtype=float32),
 array([ 0.11768586], dtype=float32),
 array([ 0.00088383], dtype=float32),
 array([ 0.00087969], dtype=float32),
 array([ 0.0008799],

In [23]:
X_test

array([[5591],
       [   0],
       [2721],
       ..., 
       [   3],
       [2227],
       [ 704]])

In [24]:
Y_test

array([0, 0, 0, ..., 0, 0, 0])

In [25]:
print(max(predict))
print(min(predict))

[ 0.93876731]
[ 0.00087941]


In [26]:
for nt in range(200):
    print(res[nt])

[ 0.11464844]
[ 0.0008852]
[ 0.12474378]
[ 0.00088713]
[ 0.10934579]
[ 0.0008852]
[ 0.00088389]
[ 0.12223373]
[ 0.0008852]
[ 0.11672376]
[ 0.0008852]
[ 0.11420792]
[ 0.00088744]
[ 0.0008852]
[ 0.00088389]
[ 0.08856998]
[ 0.0008852]
[ 0.09095952]
[ 0.00089161]
[ 0.0008852]
[ 0.00088389]
[ 0.10054669]
[ 0.0008852]
[ 0.11768586]
[ 0.00088383]
[ 0.00087969]
[ 0.0008799]
[ 0.00090544]
[ 0.00088044]
[ 0.00088472]
[ 0.00087941]
[ 0.11095794]
[ 0.00089941]
[ 0.0008821]
[ 0.00632886]
[ 0.12757371]
[ 0.00956571]
[ 0.04433959]
[ 0.00088304]
[ 0.00088096]
[ 0.00088161]
[ 0.0008852]
[ 0.00088099]
[ 0.05088131]
[ 0.00088536]
[ 0.0008824]
[ 0.00088309]
[ 0.00088912]
[ 0.00088459]
[ 0.0008852]
[ 0.11768586]
[ 0.00087969]
[ 0.0008799]
[ 0.77541745]
[ 0.00089197]
[ 0.13321678]
[ 0.11095794]
[ 0.00088304]
[ 0.00088096]
[ 0.0008852]
[ 0.00088386]
[ 0.10776068]
[ 0.00088096]
[ 0.00088513]
[ 0.00089553]
[ 0.93869209]
[ 0.45733437]
[ 0.00632886]
[ 0.93819761]
[ 0.29073229]
[ 0.0008797]
[ 0.10862629]
[ 0.0063

In [37]:
tx_cnt = 0 # timex count by LSTM-RNN system

extracted_timex = []

serial_list_of_extracted_timex = [] 

for i in range(len(test)):
    
    if(predict[i] >0.19):
        extracted_timex.append(Z_test[i])
        serial_list_of_extracted_timex.append(i)
        print(Z_test[i])
        tx_cnt = tx_cnt + 1
  
        
print(sep)        
print(tx_cnt)
print(sep)

now
Aug.
26
Oct.
20
Aug.
10
1988
months
two-year
earlier
this
month
three
currently
second
three
late
yesterday
year
July
2
second
this
year
current
12
Sept.
30
Earlier
this
month
10
third
quarter
third-quarter
mid-November
fiscal
year
year
December
year-ago
quarter
second
quarter
Oct.
31
26
quarter
first
today
Nov.
Jan.
1
1990
third
quarter
Aug.
third
quarter
year-earlier
third
quarter
June
past
Nov.
1
two
first
last
week
1
yesterday
Tuesday
five
late
yesterday
Tuesday
yesterday
Dec.
31
1990
next
14
months
1984
early
full
current
1988
week
10
two
Tuesday
early
end
last
April
yesterday
30
days
August
1988
Dec.
7
Nov.
22
yesterday
third
quarter
year-earlier
quarter
last
June
earlier
this
month
nine
months
year-earlier
period
five
Dec.
1
Nov.
10
1989
future
1990
yesterday
Last
week
past
two
months
three
past
two
months
recent
weeks
recent
years
quarter
past
two
months
last
week
week
last
month
day
two
days
every
month
last
three
years
this
month
early
September
Friday
Oct.
13
now
past
tw

In [38]:
for temp_cnt in range(len(extracted_timex)):
    print(extracted_timex[temp_cnt] , '   ' , serial_list_of_extracted_timex[temp_cnt])

print(sep)

now     53
Aug.     65
26     66
Oct.     68
20     69
Aug.     165
10     166
1988     168
months     191
two-year     199
earlier     281
this     282
month     283
three     319
currently     339
second     369
three     372
late     416
yesterday     417
year     421
July     423
2     424
second     456
this     460
year     461
current     495
12     528
Sept.     537
30     538
Earlier     557
this     558
month     559
10     568
third     603
quarter     604
third-quarter     613
mid-November     616
fiscal     627
year     628
year     632
December     634
year-ago     639
quarter     640
second     643
quarter     644
Oct.     646
31     647
26     660
quarter     674
first     749
today     800
Nov.     802
Jan.     824
1     825
1990     827
third     879
quarter     880
Aug.     916
third     963
quarter     964
year-earlier     973
third     974
quarter     975
June     1005
past     1020
Nov.     1022
1     1023
two     1035
first     1074
last     1098
week     1099
1 

In [55]:
flag = 0
normalize_list = []

for i in range(len(extracted_timex)):
    if (i>0):
        if flag ==0:
            temp_lst =[]
            temp_lst.append(extracted_timex[i-1])
        if(serial_list_of_extracted_timex[i]-serial_list_of_extracted_timex[i-1] ==1):
            temp_lst.append(extracted_timex[i])
            flag =1
        elif( 
            flag==1 and extracted_timex[i-1].isnumeric() and 
            extracted_timex[i].isnumeric() and
            (serial_list_of_extracted_timex[i]-serial_list_of_extracted_timex[i-1] ==2)
        ):
            temp_lst.append(extracted_timex[i])
        else:
            flag = 0
        normalize_list.append(temp_lst)
print(sep)

final_nomalize_list =[]
def unique_list(arg_lst):
    x = []
    for timex in arg_lst:
        if timex not in x:
            x.append(timex)
    return x

final_nomalize_list = unique_list(normalize_list)
print(final_nomalize_list )

print(sep)

[['now'], ['Aug.', '26'], ['Oct.', '20'], ['Aug.', '10', '1988'], ['months'], ['two-year'], ['earlier', 'this', 'month'], ['three'], ['currently'], ['second'], ['late', 'yesterday'], ['year'], ['July', '2'], ['this', 'year'], ['current'], ['12'], ['Sept.', '30'], ['Earlier', 'this', 'month'], ['10'], ['third', 'quarter'], ['third-quarter'], ['mid-November'], ['fiscal', 'year'], ['December'], ['year-ago', 'quarter'], ['second', 'quarter'], ['Oct.', '31'], ['26'], ['quarter'], ['first'], ['today'], ['Nov.'], ['Jan.', '1', '1990'], ['Aug.'], ['year-earlier', 'third', 'quarter'], ['June'], ['past'], ['Nov.', '1'], ['two'], ['last', 'week'], ['1'], ['yesterday'], ['Tuesday'], ['five'], ['late'], ['Dec.', '31', '1990'], ['next', '14', 'months'], ['1984'], ['early'], ['full'], ['1988'], ['week'], ['end'], ['last', 'April'], ['30', 'days'], ['August', '1988'], ['Dec.', '7'], ['Nov.', '22'], ['year-earlier', 'quarter'], ['last', 'June'], ['nine', 'months'], ['year-earlier', 'period'], ['Dec.', 

In [58]:
taged_list =[]
for element in range(len(final_nomalize_list)):
    strng =''
    for i in range(len(final_nomalize_list[element])):
        strng = strng+' '+final_nomalize_list[element][i]
    taged_strng = '<TIMEX3> ' + strng +'  </TIMEX3>'
    taged_list.append(taged_strng)

for elem in range(len(taged_list)):
    print(taged_list[elem])

<TIMEX3>  now  </TIMEX3>
<TIMEX3>  Aug. 26  </TIMEX3>
<TIMEX3>  Oct. 20  </TIMEX3>
<TIMEX3>  Aug. 10 1988  </TIMEX3>
<TIMEX3>  months  </TIMEX3>
<TIMEX3>  two-year  </TIMEX3>
<TIMEX3>  earlier this month  </TIMEX3>
<TIMEX3>  three  </TIMEX3>
<TIMEX3>  currently  </TIMEX3>
<TIMEX3>  second  </TIMEX3>
<TIMEX3>  late yesterday  </TIMEX3>
<TIMEX3>  year  </TIMEX3>
<TIMEX3>  July 2  </TIMEX3>
<TIMEX3>  this year  </TIMEX3>
<TIMEX3>  current  </TIMEX3>
<TIMEX3>  12  </TIMEX3>
<TIMEX3>  Sept. 30  </TIMEX3>
<TIMEX3>  Earlier this month  </TIMEX3>
<TIMEX3>  10  </TIMEX3>
<TIMEX3>  third quarter  </TIMEX3>
<TIMEX3>  third-quarter  </TIMEX3>
<TIMEX3>  mid-November  </TIMEX3>
<TIMEX3>  fiscal year  </TIMEX3>
<TIMEX3>  December  </TIMEX3>
<TIMEX3>  year-ago quarter  </TIMEX3>
<TIMEX3>  second quarter  </TIMEX3>
<TIMEX3>  Oct. 31  </TIMEX3>
<TIMEX3>  26  </TIMEX3>
<TIMEX3>  quarter  </TIMEX3>
<TIMEX3>  first  </TIMEX3>
<TIMEX3>  today  </TIMEX3>
<TIMEX3>  Nov.  </TIMEX3>
<TIMEX3>  Jan. 1 1990  </TIM

In [40]:
count_timex = 0  # referred timex

timex3_tokens = []

for tok in range(len(Y_test)):
    if Y_test[tok] == 1:
        count_timex = count_timex + 1
        timex3_tokens.append(Z_test[tok])
  
        
print(count_timex)
print(sep)

775


In [41]:
print(len(timex3_tokens))
print(len(extracted_timex))

775
725


In [42]:
number_of_pure_extracted_timex = 0

for tk in range(len(extracted_timex)):
    if extracted_timex[tk] in timex3_tokens:
        number_of_pure_extracted_timex  = number_of_pure_extracted_timex  +1 
        
print(number_of_pure_extracted_timex )

698


In [43]:
precision = number_of_pure_extracted_timex/ len(extracted_timex)

In [44]:
precision

0.9627586206896551

In [45]:
recall = number_of_pure_extracted_timex / len(timex3_tokens)

In [46]:
recall

0.9006451612903226

In [47]:
f1_Score = 2*precision*recall / (precision+ recall)

In [57]:
f1_Score

0.9306666666666668